package com.quizapu.spring.config.model;

public enum NombreTipoDeUsuario {

	ADMINISTRADOR_DE_SISTEMA, CLIENTE, EJECUTIVO_DE_ATENCION_A_CLIENTES, EJECUTIVO_DE_VENTAS, ENCARGADO_DE_BODEGA, ENCARGADO_DE_PRODUCTO, SUPERVISOR;

}
